# -*- coding: utf-8 -*-
"""ProliferatingSeries_seriesManipulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ksq-cZDFCRpo-4rhrRLrakdgAakx-wBO
"""

from math import gcd
from functools import reduce
import os
from collections import defaultdict
from itertools import permutations
from contextlib import ExitStack
from enum import Enum

class Transformation(Enum):
    #the class that defines the transformations that we apply to our series
    P = "P"
    I = "I"
    R = "R"
    RI = "RI"
    def apply(self, series:list[int], t:int, n:int)->list[int]:
        if   self == Transformation.P:  return [(x+t) % n for x in series]
        elif self == Transformation.I:  return [(-x+t) % n for x in series]
        elif self == Transformation.R:  return [(x+t) % n for x in reversed(series)]
        elif self == Transformation.RI: return [(-x+t) % n for x in reversed(series)]

class NotesConverter():
    def __init__(self):
        self.noteToInt = {"C":0, "C#":1, "Db":1,
                          "D":2, "D#":3, "Eb":3,
                          "E":4,
                          "F":5, "F#":6, "Gb":6,
                          "G":7, "G#":8, "Ab":8,
                          "A":9, "A#":10, "Bb":10,
                          "B":11}

    def convert(self, notes):
        try:
            values = [self.noteToInt[n] for n in notes]
        except KeyError as e:
              raise ValueError(f"Invalid note: {e}")
        base = values[0]
        normalized = [(x-base) % 12 for x in values]
        mapping = {v:i for i,v in enumerate(sorted(set(normalized)))}
        result = [mapping[x] for x in normalized]
        reverseMapping = {result[i]:notes[i] for i in range(len(notes))}
        return result, reverseMapping


def proliferatingPermutation(transformation:Transformation, series:list[int], t:int, n:int)->list[int]:
    #calculates the permutations obtained from series by appliyng transformation and transposition t.
    #The permutation is stored as a list[int] so that permutations[i] yields the note in the transformed
    #series that is in the same place that i was in the original series
    transformed = transformation.apply(series, t, n)
    index = {value: i for (i, value) in enumerate(series)}
    return [transformed[index[value]] for value in range(n)]

def lcm_list(series:list[int])->int:
    return reduce(lambda a,b: a*b//gcd(a,b), series)

def cycleStructure(permutation:list[int],n:int)->(int,list[int]):
    #calculates the lengths of the cycles of the permutation. Returns the order of the permutation and
    #a list with the lengths of the cycles
    visited = [False]*n
    cycles = []
    for i in range(n):
        if not visited[i]:
            current=permutation[i]
            length=1
            while current!=i:
                visited[current]=True
                current=permutation[current]
                length+=1
            cycles.append(length)
    return lcm_list(cycles), sorted(cycles)

def print_justified(series):
    width = max(len(str(x)) for x in series)
    print("[" + ", ".join(f"{str(x):<{width}}" for x in series) + "]")

def proliferations(transformation:Transformation, series:list[int], t:int,flag=False)->None:
    #first major program: takes a transformation with a transposition t and a series (and translates
    #it from notes to numbers if necessary). Prints the original and all its proliferations.
    #Also prints the order and the structure of the permutation obtained
    if isinstance(series[0],str):
        flag = True
        converter = NotesConverter()
        series,reverseMapping = converter.convert(series)
    else:
        reverseMapping = {i:i for i in series}
    print("Proliferations of the series using", transformation.name,"and a transposition of", t, "tone-fractions:")
    print_justified([reverseMapping[i] for i in series])
    n=len(series)
    permutation = proliferatingPermutation(transformation, series, t, n)
    current = [permutation[x] for x in series]
    while current != series:
        print_justified([reverseMapping[i] for i in current])
        current = [permutation[x] for x in current]
    (order,cycles)=cycleStructure(permutation,n)
    print("Order:", order)
    print("Structure:", cycles)
    if flag:
        print("-------------")
        print("Identification of notes and numbers:")
        width = max(len(str(k)) for k,v in reverseMapping.items())
        for k,v in reverseMapping.items():
            print(f"{k:<{width}} <---> {v}")

def proliferations_data(transformation:Transformation, t:int, n:int, path:str)->None:
    #second major program: takes a transformation, a transposition t, a number of notes n and a path.
    #The program creates in this path a folder for the transformation, another folder inside for the
    #number of notes and 3 more subfolders inside it, called "CompleteList", "Data_Orders" and
    #"Data_Structures". Finally, a txt file inside each of them distinguishing the transposition t.
    #The file in "CompleteList" shows every possible series starting with 0 and the number of proliferations
    #that it produces (a file with a very large size, you may not want it). The file in "Data_Orders" shows how many series generate permutations of each possible
    #order, and the file in "Data_Structures" shows how many series generate permutations of each possible
    #structure.
    base_path = os.path.join(path, transformation.name, f"Proliferations_{n}_notes")
    dirs = {
        "Data_Structures": os.path.join(base_path, "Data_Structures"),
        #"CompleteList": os.path.join(base_path, "CompleteList"),   #<--------- uncomment if you want the CompleteList
        "Data_Orders": os.path.join(base_path, "Data_Orders")
    }
    for d in dirs.values():
        os.makedirs(d, exist_ok=True)
    file_paths = {key: os.path.join(dirs[key], f"transposition{t}.txt") for key in dirs}
    occurrence_orders = defaultdict(int)
    occurrence_structures = defaultdict(int)
    with ExitStack() as stack:
        files = {key: stack.enter_context(open(file_paths[key], "w")) for key in file_paths}
        for seriesWithout0 in permutations(range(1, n)):
            completeSeries = (0,) + (seriesWithout0)
            permutation = proliferatingPermutation(transformation, completeSeries, t, n)
            order, structure = cycleStructure(permutation, n)
            #files["CompleteList"].write(f"{completeSeries} --> {order}\n")  #<--- uncomment if you want the CompleteList with the proliferations of each possible series
            occurrence_orders[order] += n #we sum n rather than 1 since we are only considering series that start with 0, so each will appear n times more
            occurrence_structures[(order, tuple(structure))] += n
        for k, v in sorted(occurrence_orders.items()):
            files["Data_Orders"].write(f"{k}: {v}\n")
        for k, v in sorted(occurrence_structures.items()):
            files["Data_Structures"].write(f"{k}: {v}\n")

#Examples used in the article:

# Stockhausen in freundschtaft
series1 = ["C", "F", "E", "C#", "B", "Bb", "Eb", "Ab", "D", "G", "A", "F#"]

# Op. 31 schoenberg
series2 = ["Bb", "E", "F#", "D#", "F", "A", "D", "C#", "G", "G#", "B", "C"]

# Op. 24 Webern
series3 = ["B", "Bb", "D", "Eb", "G", "F#", "G#", "E", "F", "C", "C#", "A"]

# Denisov sonata
series4 = ["B", "C", "A", "G#", "A#", "F", "F#", "G", "E", "D#", "C#", "D"]

# Symphony Webern
series5 = ["A", "F#", "G", "Ab", "E", "F", "B", "Bb", "D", "C#", "C", "Eb"]

# Acento en rosa
series6 = ["G", "C", "F#", "G#", "D#", "E", "A", "C#", "D", "F", "B", "A#"]

# Au dela du hazard
series7 = ["C", "G#", "G", "C#", "E", "D", "A#", "D#", "B", "F", "F#", "A"]

proliferations(Transformation.I, ["G", "C", "F#", "G#", "D#", "E", "A", "C#", "D", "F", "B", "A#"], 2)

#You can also input the list with numbers
proliferations(Transformation.P,[0, 5, 4, 1, 11, 10, 3, 8, 2, 7, 9, 6],1)

proliferations(Transformation.P,series3,4)

proliferations(Transformation.RI,series7,2)

proliferations(Transformation.RI,[0, 6, 8, 5, 7, 11, 4, 3, 9, 10, 1, 2],5)

proliferations(Transformation.RI,[0,5,3,2,6,1,4],0)

proliferations(Transformation.R,series1,1)

proliferations(Transformation.R,series4,2)

#Running proliferations_data in a loop for each transformation, n in range(1,max+1) and t in range(0,n)
#gives all this data of proliferating series up to the desired number of notes max.
#Don't forget to change "desiredFolder" to the actual folder you want the files in.

#Currently it will run for all series up to 12 notes, which is quite slow, at least several hours running.

#The completeList folders are occupy several GB for n=12, since they show every possible series, so if you don't want them, just
#comment (put a # in the beggining of the line) the lines that are highlighted with an arrow <------------
#The folder Proliferations_data in this repository has the files that running this program creates, including the cases of
#P and I, and excluding the CompleteList folders.

for n in range(1,10):
    for t in range(0,n):
        proliferations_data(Transformation.RI,t,n,r"desiredFolder")
        proliferations_data(Transformation.R ,t,n,r"desiredFolder")
        proliferations_data(Transformation.P ,t,n,r"desiredFolder")
        proliferations_data(Transformation.I ,t,n,r"desiredFolder")
        #Running it for P and I will give us useless information, since the permutations are essentially independent of the specific series

